development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: social_network
  username: social_network
  password: <%= ENV['SOCIAL_NETWORK_DATABASE_PASSWORD'] %>
